### ISSUE TITLE
注文ステータス一覧の

### ISSUE THREAD

**Issue by iskou9821** [HirokazuNishi/Magento-Japanese-Translation#12]
管理画面の「注文ステータス」のメンテナンス画面で、「未割り当て」というActionがありますが、「割り当て解除」のような表現の方が分かりやすいのではないでしょうか。

<img width="1094" alt="20150714_1" src="https://cloud.githubusercontent.com/assets/6629303/8668748/477662b2-2a49-11e5-8f85-05e3438ae9de.png">

**Comment by HirokazuNishi** [comment]
なるほど、じゃあ1.9.2対応と合わせて調整します。

**Comment by HirokazuNishi** [comment]
割当解除に変えました。
